server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.format_sql: true
  flyway.enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fever
    username: postgres
    password: postgres
