spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

fever:
  provider:
    base-url: https://provider.code-challenge.feverup.com/api/events
    timeout-ms: 10000
