spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fever
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
fever:
  provider:
    base-url: https://provider.code-challenge.feverup.com/api/events
    connect-timeout-ms: 5000
    read-timeout-ms: 5000
  search:
    warmup-ms: 400
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

resilience4j:
  circuitbreaker:
    instances:
      provider:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      provider:
        max-attempts: 3
        wait-duration: 300ms