-- V1: initial schema (H2-friendly)

CREATE TABLE IF NOT EXISTS plans (
  -- BIGSERIAL (PostgreSQL) -> BIGINT IDENTITY (H2)
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  provider_id VARCHAR(128) NOT NULL UNIQUE,
  -- H2 admite TEXT como alias de CLOB; si prefieres, usa VARCHAR(255)
  title TEXT NOT NULL,
  sell_mode VARCHAR(16) NOT NULL,

  -- TIMESTAMPTZ (PostgreSQL) -> TIMESTAMP WITH TIME ZONE (H2)
  starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ends_at   TIMESTAMP WITH TIME ZONE NOT NULL,

  min_price DOUBLE PRECISION,
  max_price DOUBLE PRECISION,

  first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
  last_seen_at  TIMESTAMP WITH TIME ZONE NOT NULL,

  currently_available BOOLEAN NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_plans_window  ON plans (starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_plans_sellmode ON plans (sell_mode);
